#!/bin/bash

# project 1
# numpy_mnist

train_images=$1
train_labels=$2
test_images=$3
test_labels=$4

python assignment1.py $train_images $train_labels $test_images $test_labels
#
# Fill in the empty line below with the command or commands that run your
# program.
# For example, you could pass this script's arguments to your program as:
#   python <myprogram> $train_images $train_labels $test_images $test_labels
#
# with <myprogram> replaced with your program name.
#
#   If you are having difficulty getting the script to run your program, talk
# to the TAs.
##############################################################################

##############################################################################
# Run this script with the command
#
#   ./numpy_mnist path-to-train-images.gz path-to-train-labels.gz path-to-test-images.gz path-to-test-labels.gz


